### ISSUE TITLE
Cannot login in blender

### ISSUE THREAD

**Issue by kjhyhy6765** [sketchfab/blender-plugin#45]
when viewing the sidebar and opening the sketchfab plugin and pop down the log in menu its locked 10% open and wont reveal the whole bar. I cant type, I've tried re installing, different blender versions...

![image](https://user-images.githubusercontent.com/84518334/126346670-cee74385-5a5b-4fcd-b52c-f72be7fa0082.png)

**Comment by kjhyhy6765** [comment]
fixed it, installed the newest version

**Comment by grimmoxy** [comment]
bro, i have the same problem. tried multiple times. Please help.

**Comment by HisakoDarkFire** [comment]
im also getting the same problem

**Comment by YouthfulPat501** [comment]
yup me too

**Comment by Kazooskii** [comment]
To the people still having problems with this, I was able to fix my issue by installing this version:
https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0

My blender version is 3.6.4
I hope this helps you guys!
